"""Configuration API endpoints."""
import os
import re
import subprocess
import tempfile
from urllib.parse import urlparse

from fastapi import APIRouter, Depends, HTTPException, Query

from ..config import get_settings, Settings
from ..dependencies import verify_credentials
from ..models.schemas import ConfigUpdate, ConfigResponse, TestNotificationRequest, NotificationResponse
from utils.helpers import list_installed_selectable_models, model_supports_species_filter

router = APIRouter()
APPRISE_CONFIG_FILENAME = 'apprise.txt'
APPRISE_BODY_FILENAME = 'body.txt'


def configured_birdnet_user(settings: Settings) -> str:
    return settings.config.get('BIRDNET_USER') or os.environ.get('USER', 'pi')


def run_managed_script(args: list[str], timeout: int, failure_detail: str) -> subprocess.CompletedProcess:
    try:
        result = subprocess.run(
            args,
            capture_output=True,
            text=True,
            timeout=timeout,
            check=False,
        )
    except subprocess.TimeoutExpired:
        raise HTTPException(status_code=500, detail=f"{failure_detail}: operation timed out")
    except Exception as exc:
        raise HTTPException(status_code=500, detail=f"{failure_detail}: {exc}")

    if result.returncode != 0:
        detail = result.stderr.strip() or result.stdout.strip() or "unknown error"
        raise HTTPException(status_code=500, detail=f"{failure_detail}: {detail}")

    return result


def sync_language_labels(settings: Settings) -> None:
    script_path = os.path.join(settings.base_path, 'scripts', 'install_language_label.sh')
    run_managed_script(
        ['sudo', '-u', configured_birdnet_user(settings), script_path],
        timeout=30,
        failure_detail="Failed to update model labels",
    )


def restart_services(settings: Settings) -> None:
    script_path = os.path.join(settings.base_path, 'scripts', 'restart_services.sh')
    run_managed_script(
        ['sudo', script_path],
        timeout=60,
        failure_detail="Failed to restart services",
    )


def caddy_site_addresses(raw_url: str) -> str:
    """Build the Caddy site-address line from the configured public URL."""
    candidate = (raw_url or '').strip().rstrip('/')
    if not candidate:
        return 'http://'

    parsed = urlparse(candidate if '://' in candidate else f'https://{candidate}')
    host = (parsed.netloc or parsed.path).strip().rstrip('/')
    if not host:
        return 'http://'

    return f'http:// {host}'


def update_caddy_config(settings: Settings) -> None:
    """Regenerate the FastAPI Caddyfile and reload Caddy."""
    auth_block = ''
    if settings.caddy_password:
        hash_result = run_managed_script(
            ['caddy', 'hash-password', '--plaintext', settings.caddy_password],
            timeout=10,
            failure_detail="Failed to hash Caddy password",
        )
        hashword = hash_result.stdout.strip()
        auth_block = f"""
  basicauth /api/config* {{
    birdnet {hashword}
  }}
  @protected_system {{
    path /api/system*
    not path /api/system/public-status*
  }}
  basicauth @protected_system {{
    birdnet {hashword}
  }}
  basicauth /settings* {{
    birdnet {hashword}
  }}"""

    caddyfile = f"""# BirdNET-Pi Caddy Configuration
# Generated by config API

{{
    admin off
}}

{caddy_site_addresses(settings.birdnetpi_url)} {{
    @blocked_legacy_probe_paths {{
        path_regexp legacyProbe (?i)(^|/)[^/]+\\.(php[0-9]?|phtml|phar|phps|phtm?)(/|$)|^/(\\.git|\\.env)(/|\\.|$)
    }}
    respond @blocked_legacy_probe_paths 404

    reverse_proxy localhost:8080
    {auth_block}

    encode gzip

    log {{
        output file /var/log/caddy/birdnet.log {{
            roll_size 10mb
            roll_keep 5
        }}
    }}
}}
"""

    with tempfile.NamedTemporaryFile(mode='w', delete=False, encoding='utf-8') as tmp:
        tmp.write(caddyfile)
        tmp_path = tmp.name

    try:
        run_managed_script(
            ['sudo', 'cp', tmp_path, '/etc/caddy/Caddyfile'],
            timeout=10,
            failure_detail="Failed to write Caddyfile",
        )
        run_managed_script(
            ['sudo', 'caddy', 'fmt', '--overwrite', '/etc/caddy/Caddyfile'],
            timeout=10,
            failure_detail="Failed to format Caddyfile",
        )
        run_managed_script(
            ['sudo', 'systemctl', 'reload', 'caddy'],
            timeout=20,
            failure_detail="Failed to reload Caddy",
        )
    finally:
        os.unlink(tmp_path)


def notification_file_path(settings: Settings, filename: str) -> str:
    return os.path.join(settings.base_path, filename)


def read_notification_file(settings: Settings, filename: str) -> str:
    path = notification_file_path(settings, filename)
    try:
        with open(path, 'r', encoding='utf-8') as handle:
            return handle.read()
    except FileNotFoundError:
        return ''


def write_notification_file(settings: Settings, filename: str, contents: str) -> None:
    path = notification_file_path(settings, filename)
    with open(path, 'w', encoding='utf-8') as handle:
        handle.write(contents)


def serialize_config_value(field: str, key: str, value) -> str:
    if field == 'activate_freqshift_in_livestream':
        rendered = '"true"' if value else '"false"'
    elif isinstance(value, bool):
        rendered = '1' if value else '0'
    elif isinstance(value, str):
        rendered = f'{key}="{value}"'
        return rendered
    else:
        rendered = str(value)

    return f'{key}={rendered}'


@router.get("/config", response_model=ConfigResponse)
async def get_config(
    user: str = Depends(verify_credentials),
    settings: Settings = Depends(get_settings),
):
    """Get current configuration.

    Requires authentication. Returns a safe subset of settings.
    """
    return ConfigResponse(
        site_name=settings.site_name,
        latitude=settings.latitude,
        longitude=settings.longitude,
        database_lang=settings.database_lang,
        color_scheme=settings.color_scheme,
        update_channel=settings.update_channel,
        model=settings.model,
        sf_thresh=settings.sf_thresh,
        data_model_version=settings.data_model_version,
        confidence=settings.confidence,
        sensitivity=settings.sensitivity,
        overlap=settings.overlap,
        birdweather_id=settings.birdweather_id,
        info_site=settings.info_site,
        image_provider=settings.image_provider,
        has_flickr_key=bool(settings.flickr_api_key),
        flickr_filter_email=settings.flickr_filter_email,
        password_configured=bool(settings.caddy_password),
        birdnetpi_url=settings.birdnetpi_url,
        rtsp_stream=settings.rtsp_stream,
        rtsp_stream_to_livestream=settings.rtsp_stream_to_livestream,
        activate_freqshift_in_livestream=settings.activate_freqshift_in_livestream,
        apprise_config=read_notification_file(settings, APPRISE_CONFIG_FILENAME),
        apprise_notification_title=settings.apprise_notification_title,
        apprise_notification_body=read_notification_file(settings, APPRISE_BODY_FILENAME),
        apprise_notify_each_detection=settings.apprise_notify_each_detection,
        apprise_notify_new_species=settings.apprise_notify_new_species,
        apprise_notify_new_species_each_day=settings.apprise_notify_new_species_each_day,
        apprise_weekly_report=settings.apprise_weekly_report,
        apprise_minimum_seconds_between_notifications_per_species=settings.apprise_minimum_seconds_between_notifications_per_species,
        apprise_only_notify_species_names=settings.apprise_only_notify_species_names,
        apprise_only_notify_species_names_2=settings.apprise_only_notify_species_names_2,
        privacy_threshold=settings.privacy_threshold,
        full_disk=settings.full_disk,
        purge_threshold=settings.purge_threshold,
        max_files_species=settings.max_files_species,
        rec_card=settings.rec_card,
        channels=settings.channels,
        recording_length=settings.recording_length,
        extraction_length=settings.extraction_length,
        audiofmt=settings.audiofmt,
        silence_update_indicator=settings.silence_update_indicator,
        automatic_update=settings.automatic_update,
        raw_spectrogram=settings.raw_spectrogram,
        rare_species_threshold=settings.rare_species_threshold,
        custom_image=settings.custom_image,
        custom_image_title=settings.custom_image_title,
        freqshift_tool=settings.freqshift_tool,
        freqshift_hi=settings.freqshift_hi,
        freqshift_lo=settings.freqshift_lo,
        freqshift_reconnect_delay=settings.freqshift_reconnect_delay,
        freqshift_pitch=settings.freqshift_pitch,
        log_level_birdnet_recording_service=settings.log_level_birdnet_recording_service,
        log_level_live_audio_stream_service=settings.log_level_live_audio_stream_service,
        log_level_spectrogram_viewer_service=settings.log_level_spectrogram_viewer_service,
    )


@router.put("/config")
async def update_config(
    config_update: ConfigUpdate,
    user: str = Depends(verify_credentials),
    settings: Settings = Depends(get_settings),
):
    """Update configuration.

    Requires authentication. Only updates fields that are provided.
    """
    config_path = settings.config_path
    previous_model = settings.model
    previous_language = settings.database_lang
    installed_models = list_installed_selectable_models()

    if config_update.model is not None and config_update.model not in installed_models:
        raise HTTPException(
            status_code=400,
            detail={
                "message": f"Unsupported model: {config_update.model}",
                "available_models": installed_models,
            },
        )

    # Read current config file
    try:
        with open(config_path, 'r') as f:
            contents = f.read()
    except FileNotFoundError:
        raise HTTPException(status_code=500, detail="Configuration file not found")
    except PermissionError:
        raise HTTPException(status_code=500, detail="Cannot read configuration file")

    # Map of field names to config keys
    field_map = {
        'site_name': 'SITE_NAME',
        'latitude': 'LATITUDE',
        'longitude': 'LONGITUDE',
        'database_lang': 'DATABASE_LANG',
        'color_scheme': 'COLOR_SCHEME',
        'update_channel': 'UPDATE_CHANNEL',
        'info_site': 'INFO_SITE',
        'model': 'MODEL',
        'sf_thresh': 'SF_THRESH',
        'data_model_version': 'DATA_MODEL_VERSION',
        'confidence': 'CONFIDENCE',
        'sensitivity': 'SENSITIVITY',
        'overlap': 'OVERLAP',
        'birdweather_id': 'BIRDWEATHER_ID',
        'flickr_api_key': 'FLICKR_API_KEY',
        'flickr_filter_email': 'FLICKR_FILTER_EMAIL',
        'image_provider': 'IMAGE_PROVIDER',
        'caddy_password': 'CADDY_PWD',
        'birdnetpi_url': 'BIRDNETPI_URL',
        'rtsp_stream': 'RTSP_STREAM',
        'rtsp_stream_to_livestream': 'RTSP_STREAM_TO_LIVESTREAM',
        'activate_freqshift_in_livestream': 'ACTIVATE_FREQSHIFT_IN_LIVESTREAM',
        'apprise_notification_title': 'APPRISE_NOTIFICATION_TITLE',
        'apprise_notify_each_detection': 'APPRISE_NOTIFY_EACH_DETECTION',
        'apprise_notify_new_species': 'APPRISE_NOTIFY_NEW_SPECIES',
        'apprise_notify_new_species_each_day': 'APPRISE_NOTIFY_NEW_SPECIES_EACH_DAY',
        'apprise_weekly_report': 'APPRISE_WEEKLY_REPORT',
        'apprise_minimum_seconds_between_notifications_per_species': 'APPRISE_MINIMUM_SECONDS_BETWEEN_NOTIFICATIONS_PER_SPECIES',
        'apprise_only_notify_species_names': 'APPRISE_ONLY_NOTIFY_SPECIES_NAMES',
        'apprise_only_notify_species_names_2': 'APPRISE_ONLY_NOTIFY_SPECIES_NAMES_2',
        'privacy_threshold': 'PRIVACY_THRESHOLD',
        'full_disk': 'FULL_DISK',
        'purge_threshold': 'PURGE_THRESHOLD',
        'max_files_species': 'MAX_FILES_SPECIES',
        'rec_card': 'REC_CARD',
        'channels': 'CHANNELS',
        'recording_length': 'RECORDING_LENGTH',
        'extraction_length': 'EXTRACTION_LENGTH',
        'audiofmt': 'AUDIOFMT',
        'silence_update_indicator': 'SILENCE_UPDATE_INDICATOR',
        'automatic_update': 'AUTOMATIC_UPDATE',
        'raw_spectrogram': 'RAW_SPECTROGRAM',
        'rare_species_threshold': 'RARE_SPECIES_THRESHOLD',
        'custom_image': 'CUSTOM_IMAGE',
        'custom_image_title': 'CUSTOM_IMAGE_TITLE',
        'freqshift_tool': 'FREQSHIFT_TOOL',
        'freqshift_hi': 'FREQSHIFT_HI',
        'freqshift_lo': 'FREQSHIFT_LO',
        'freqshift_reconnect_delay': 'FREQSHIFT_RECONNECT_DELAY',
        'freqshift_pitch': 'FREQSHIFT_PITCH',
        'log_level_birdnet_recording_service': 'LogLevel_BirdnetRecordingService',
        'log_level_live_audio_stream_service': 'LogLevel_LiveAudioStreamService',
        'log_level_spectrogram_viewer_service': 'LogLevel_SpectrogramViewerService',
    }

    # Update config values
    updates = config_update.model_dump(exclude_unset=True)
    file_updates: dict[str, str] = {}
    if 'apprise_config' in updates:
        file_updates[APPRISE_CONFIG_FILENAME] = updates.pop('apprise_config') or ''
    if 'apprise_notification_body' in updates:
        file_updates[APPRISE_BODY_FILENAME] = updates.pop('apprise_notification_body') or ''

    for field, value in updates.items():
        if field not in field_map:
            continue

        key = field_map[field]
        if field == 'extraction_length' and value is None:
            new_value = f'{key}=""'
        elif value is None:
            continue
        else:
            new_value = serialize_config_value(field, key, value)

        # Replace or add the setting
        pattern = rf'^{re.escape(key)}=.*$'
        if re.search(pattern, contents, re.MULTILINE):
            contents = re.sub(pattern, new_value, contents, flags=re.MULTILINE)
        else:
            contents += f'\n{new_value}'

    # Write updated config
    try:
        with open(config_path, 'w') as f:
            f.write(contents)
    except PermissionError:
        # Try with sudo
        with tempfile.NamedTemporaryFile(mode='w', delete=False) as tmp:
            tmp.write(contents)
            tmp_path = tmp.name

        try:
            subprocess.run(['sudo', 'cp', tmp_path, config_path], check=True)
        finally:
            os.unlink(tmp_path)

    for filename, file_contents in file_updates.items():
        write_notification_file(settings, filename, file_contents)

    # Reload settings
    settings.reload()
    applied_actions = []

    if settings.model != previous_model or settings.database_lang != previous_language:
        sync_language_labels(settings)
        applied_actions.append('labels_updated')

    if 'birdnetpi_url' in updates or 'caddy_password' in updates:
        update_caddy_config(settings)
        applied_actions.append('caddy_reloaded')

    restart_services(settings)
    applied_actions.append('services_restarted')

    return {
        "message": "Configuration updated and services restarted",
        "updated_fields": list(updates.keys()),
        "applied_actions": applied_actions,
    }


@router.post("/config/test-notification", response_model=NotificationResponse)
async def test_notification(
    request: TestNotificationRequest,
    user: str = Depends(verify_credentials),
    settings: Settings = Depends(get_settings),
):
    """Send a test notification.

    Requires authentication.
    """
    # Use the existing send_test_notification.py script
    script_path = os.path.join(settings.base_path, 'scripts', 'send_test_notification.py')
    python_path = os.path.join(settings.base_path, 'birdnet', 'bin', 'python3')

    if not os.path.exists(script_path):
        raise HTTPException(status_code=500, detail="Notification script not found")

    title = request.title or settings.apprise_notification_title
    body_contents = request.body if request.body is not None else read_notification_file(settings, APPRISE_BODY_FILENAME)
    config_contents = request.config if request.config is not None else read_notification_file(settings, APPRISE_CONFIG_FILENAME)

    with tempfile.NamedTemporaryFile(mode='w', delete=False, encoding='utf-8') as body_file:
        body_file.write(body_contents)
        body_path = body_file.name

    with tempfile.NamedTemporaryFile(mode='w', delete=False, encoding='utf-8') as config_file:
        config_file.write(config_contents)
        config_path = config_file.name

    cmd = [python_path, script_path, '--config', config_path, '--title', title, '--body', body_path]

    try:
        result = subprocess.run(cmd, capture_output=True, text=True, timeout=30)

        if result.returncode == 0:
            return NotificationResponse(
                success=True,
                message="Test notification sent successfully",
            )
        else:
            return NotificationResponse(
                success=False,
                message=f"Notification failed: {result.stderr or result.stdout}",
            )
    except subprocess.TimeoutExpired:
        return NotificationResponse(
            success=False,
            message="Notification timed out",
        )
    except Exception as e:
        return NotificationResponse(
            success=False,
            message=f"Error sending notification: {str(e)}",
        )
    finally:
        for path in (body_path, config_path):
            try:
                os.unlink(path)
            except FileNotFoundError:
                pass


@router.get("/config/models")
async def list_available_models(
    settings: Settings = Depends(get_settings),
):
    """List available BirdNET models."""
    models = [
        {
            "name": model_name,
            "active": model_name == settings.model,
            "supports_species_filter": model_supports_species_filter(model_name),
        }
        for model_name in list_installed_selectable_models()
    ]

    return {"models": models, "current": settings.model}


@router.get("/config/languages")
async def list_available_languages(
    settings: Settings = Depends(get_settings),
):
    """List available display languages."""
    l18n_dir = os.path.join(settings.model_path, 'l18n')

    languages = []
    for filename in os.listdir(l18n_dir):
        if filename.startswith('labels_') and filename.endswith('.json'):
            lang_code = filename.replace('labels_', '').replace('.json', '')
            languages.append({
                "code": lang_code,
                "active": lang_code == settings.database_lang,
            })

    languages.sort(key=lambda x: x['code'])

    return {"languages": languages, "current": settings.database_lang}


@router.get("/config/preview-species")
async def preview_species_list(
    threshold: float = Query(0.03, ge=0.0005, le=0.99),
    model: str | None = None,
    data_model_version: int | None = Query(None, ge=1, le=2),
    settings: Settings = Depends(get_settings),
):
    """Preview species list for a given threshold.

    Uses the species.py script to generate the list.
    """
    script_path = os.path.join(settings.base_path, 'scripts', 'species.py')
    python_path = os.path.join(settings.base_path, 'birdnet', 'bin', 'python3')
    model_name = model or settings.model
    model_version = data_model_version or settings.data_model_version

    if not model_supports_species_filter(model_name):
        raise HTTPException(status_code=400, detail=f"Model {model_name} does not support species range preview")

    cmd = [
        python_path,
        script_path,
        '--threshold',
        str(threshold),
        '--model',
        model_name,
        '--data-model-version',
        str(model_version),
        '--plain',
    ]

    try:
        result = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            timeout=60,
        )

        if result.returncode == 0:
            # Parse output - each line is a species
            species = [line.strip() for line in result.stdout.strip().split('\n') if line.strip()]
            return {
                "threshold": threshold,
                "model": model_name,
                "data_model_version": model_version,
                "count": len(species),
                "species": species,
            }
        else:
            raise HTTPException(status_code=500, detail=f"Script error: {result.stderr}")
    except subprocess.TimeoutExpired:
        raise HTTPException(status_code=500, detail="Species list generation timed out")
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))
